In [1]:
# We can use Word2vec for word embedding but if we want to do embeding for specific type data the we will train our own on keras

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten,Embedding, Activation, Dropout 
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalMaxPooling1D
import numpy as np
from numpy import array
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
df= pd.read_csv('twitter4000.csv')
df.head()

twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [7]:
df['sentiment'].value_counts()

0    2000
1    2000
Name: sentiment, dtype: int64

In [8]:
# Converting tweets into list
text= df['twitts'].tolist()
text

['is bored and wants to watch a movie  any suggestions?',
 'back in miami.  waiting to unboard ship ',
 "@misskpey awwww dnt dis brng bak memoriessss,  I thnk I'm sad. LoL",
 'ughhh i am so tired  blahhhhhhhhh',
 "@mandagoforth me bad! It's funny though. Zachary Quinto is only there for a few though.  &amp; to reply just put the @ symbol before the name!",
 "brr, i'm so cold. at the moment doing my assignment on Huntington's Disease, which is really depressing ",
 "@kevinmarquis haha yep but i really need to sleep, i feel like crap lol cant sleep when he's away  god i'm pathetic!",
 "eating some ice-cream while I try to see @peterfacinelli's followers numbre raise...not working sadly ",
 '@phatty84 just hella bored at work  lol',
 'Food poisoning blowssss ',
 "@StaciG She sent home the best guy, I'm over the show already ",
 '@shika Yeah I did. Trying to recover it now. I guess its time to retire that hardware ',
 "can't fall asleep ",
 'Padres come back from being down 6-0 &amp; we lo

In [9]:
y=df['sentiment']

In [10]:
# We are converting the text in to some numerical data
token= Tokenizer()
token.fit_on_texts(text)

In [11]:
token

In [23]:
# Number of unique words in text
vocab_size= len(token.word_index)+1
vocab_size

10135

In [13]:
# now we will use these index of each unique word
token.word_index

{'i': 1,
 'to': 2,
 'the': 3,
 'a': 4,
 'my': 5,
 'and': 6,
 'you': 7,
 'is': 8,
 'it': 9,
 'in': 10,
 'for': 11,
 'of': 12,
 'me': 13,
 'on': 14,
 'so': 15,
 'that': 16,
 "i'm": 17,
 'have': 18,
 'at': 19,
 'but': 20,
 'just': 21,
 'was': 22,
 'with': 23,
 'not': 24,
 'be': 25,
 'this': 26,
 'day': 27,
 'up': 28,
 'now': 29,
 'good': 30,
 'all': 31,
 'get': 32,
 'out': 33,
 'go': 34,
 'no': 35,
 'http': 36,
 'today': 37,
 'like': 38,
 'are': 39,
 'love': 40,
 'your': 41,
 'quot': 42,
 'too': 43,
 'lol': 44,
 'work': 45,
 'got': 46,
 "it's": 47,
 'amp': 48,
 'do': 49,
 'com': 50,
 'u': 51,
 'back': 52,
 'going': 53,
 'what': 54,
 'time': 55,
 'from': 56,
 'had': 57,
 'will': 58,
 'know': 59,
 'about': 60,
 'im': 61,
 'am': 62,
 "don't": 63,
 'can': 64,
 'one': 65,
 'really': 66,
 "can't": 67,
 'we': 68,
 'oh': 69,
 'well': 70,
 'still': 71,
 '2': 72,
 'some': 73,
 'its': 74,
 'miss': 75,
 'want': 76,
 'see': 77,
 'when': 78,
 'home': 79,
 'think': 80,
 'an': 81,
 'as': 82,
 'if': 83,
 

In [14]:
# Here is an example for first words list
x= ['i to the a and']


In [15]:
token.texts_to_sequences(x)

[[1, 2, 3, 4, 6]]

In [16]:
# Similarly implement this on text data
encoded_text= token.texts_to_sequences(text)

In [17]:
encoded_text

[[8, 304, 6, 345, 2, 191, 4, 236, 254, 3079],
 [52, 10, 1019, 206, 2, 3080, 3081],
 [3082, 1197, 668, 1955, 3083, 1956, 3084, 1, 3085, 17, 115, 44],
 [1957, 1, 62, 15, 192, 3086],
 [3087,
  13,
  113,
  47,
  328,
  136,
  3088,
  3089,
  8,
  101,
  88,
  11,
  4,
  285,
  136,
  48,
  2,
  448,
  21,
  277,
  3,
  3090,
  218,
  3,
  449],
 [3091,
  17,
  15,
  315,
  19,
  3,
  892,
  164,
  5,
  1459,
  14,
  3092,
  3093,
  386,
  8,
  66,
  1460],
 [3094,
  110,
  366,
  20,
  1,
  66,
  85,
  2,
  108,
  1,
  117,
  38,
  536,
  44,
  182,
  108,
  78,
  346,
  207,
  305,
  17,
  3095],
 [450, 73, 537, 569, 295, 1, 316, 2, 77, 3096, 367, 3097, 1461, 24, 187, 893],
 [3098, 21, 1958, 304, 19, 45, 44],
 [409, 3099, 3100],
 [3101, 132, 609, 79, 3, 193, 368, 17, 131, 3, 158, 199],
 [3102, 127, 1, 139, 226, 2, 1020, 9, 29, 1, 222, 74, 55, 2, 3103, 16, 3104],
 [67, 894, 423],
 [1959,
  119,
  52,
  56,
  211,
  159,
  387,
  669,
  48,
  68,
  255,
  1462,
  3,
  3105,
  71,
  570,
  

In [18]:
print(encoded_text)
# Now we can use this numerical data of text in keras

[[8, 304, 6, 345, 2, 191, 4, 236, 254, 3079], [52, 10, 1019, 206, 2, 3080, 3081], [3082, 1197, 668, 1955, 3083, 1956, 3084, 1, 3085, 17, 115, 44], [1957, 1, 62, 15, 192, 3086], [3087, 13, 113, 47, 328, 136, 3088, 3089, 8, 101, 88, 11, 4, 285, 136, 48, 2, 448, 21, 277, 3, 3090, 218, 3, 449], [3091, 17, 15, 315, 19, 3, 892, 164, 5, 1459, 14, 3092, 3093, 386, 8, 66, 1460], [3094, 110, 366, 20, 1, 66, 85, 2, 108, 1, 117, 38, 536, 44, 182, 108, 78, 346, 207, 305, 17, 3095], [450, 73, 537, 569, 295, 1, 316, 2, 77, 3096, 367, 3097, 1461, 24, 187, 893], [3098, 21, 1958, 304, 19, 45, 44], [409, 3099, 3100], [3101, 132, 609, 79, 3, 193, 368, 17, 131, 3, 158, 199], [3102, 127, 1, 139, 226, 2, 1020, 9, 29, 1, 222, 74, 55, 2, 3103, 16, 3104], [67, 894, 423], [1959, 119, 52, 56, 211, 159, 387, 669, 48, 68, 255, 1462, 3, 3105, 71, 570, 5, 1959, 329], [1960, 3106, 3107, 46, 3108, 3109], [3110, 1463, 70, 19, 227, 17, 28, 2], [3111, 1, 245, 212, 1961, 51, 72, 36, 146, 246, 3112, 1, 538, 20, 74, 507, 196

In [19]:
# we are limiting the text sixe 120 only
max_length=120
X= pad_sequences(encoded_text, maxlen=max_length, padding='post')

In [20]:
print(X)

[[    8   304     6 ...     0     0     0]
 [   52    10  1019 ...     0     0     0]
 [ 3082  1197   668 ...     0     0     0]
 ...
 [ 1033    21  1021 ...     0     0     0]
 [10134   134     7 ...     0     0     0]
 [   94    11   226 ...     0     0     0]]


In [21]:
X.shape

(4000, 120)

In [22]:
# X is a sequnce of words

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42, test_size=0.2, stratify=y)

In [26]:
vec_size= 300

model= Sequential()
model.add(Embedding(vocab_size, vec_size, input_length=max_length))

model.add(Conv1D(64,8, activation='relu'))
model.add(MaxPooling1D(2))
model.add(Dropout(0.2))
          
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
          
model.add(Dense(16, activation='relu'))
          
model.add(GlobalMaxPooling1D())
          
model.add(Dense(1, activation='sigmoid'))

In [27]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [28]:
%%time
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
100/100 [==============================] - 13s 118ms/step - loss: 0.6934 - accuracy: 0.5100 - val_loss: 0.6852 - val_accuracy: 0.5213
Epoch 2/5
100/100 [==============================] - 14s 139ms/step - loss: 0.6381 - accuracy: 0.6478 - val_loss: 0.6109 - val_accuracy: 0.6612
Epoch 3/5
100/100 [==============================] - 14s 136ms/step - loss: 0.4718 - accuracy: 0.7959 - val_loss: 0.6468 - val_accuracy: 0.6538
Epoch 4/5
100/100 [==============================] - 12s 117ms/step - loss: 0.2898 - accuracy: 0.8972 - val_loss: 0.7408 - val_accuracy: 0.7175
Epoch 5/5
100/100 [==============================] - 10s 104ms/step - loss: 0.1706 - accuracy: 0.9434 - val_loss: 0.7824 - val_accuracy: 0.7225
Wall time: 1min 2s


In [29]:
def get_encoded(x):
    x=token.texts_to_sequences(x)
    x=pad_sequences(x,maxlen=max_length, padding='post')
    return x

In [32]:
x= ['worst services. will not come again']

In [35]:
model.predict(get_encoded(x)).astype(int)

array([[0]])